version: "3.7"
services:
  web1:
    image: openjdk:11
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "nohup java -jar build/libs/project01-0.0.1-SNAPSHOT.jar > /dev/null 2> /dev/null < /dev/null &
    restart: on-failure
    container_name: spring
    depends_on:
      - db
      - web2

  web2:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    ports:
      - "6000:5000"
    container_name: web2
    volumes:
      - ./flask:/app
    working_dir: /app
    command: >
      bash -c "pip install pandas numpy flask tensorflow nltk konlpy && python server.py"
    restart: on-failure

  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=project01
      - MYSQL_ROOT_PASSWORD=samho101
      - TZ=Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/project01/mysql:/var/lib/mysql