version: "3.7"
services:
  spring:
    image: openjdk:11
    ports:
      - "80:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "nohup java -jar build/libs/project01-0.0.1-SNAPSHOT.jar"
    restart: on-failure
    container_name: spring
    depends_on:
      - redis
      - mysql
      - flask

  flask:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    ports:
      - "6000:5000"
    container_name: flask
    volumes:
      - ./flask:/app
    working_dir: /app
    command: >
      bash -c "pip install pandas numpy flask tensorflow nltk konlpy && python server.py"
    restart: on-failure

  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: on-failure
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=project01
      - MYSQL_ROOT_PASSWORD=samho101
      - TZ=Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/project01/mysql:/var/lib/mysql

  redis:
    image: redis
    restart: on-failure
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/project01/redis:/var/lib/redis

  spider_db:
    platform: ubuntu:18.04
    image: mariadb:10.1
    restart: always
    container_name: spider_db
    ports:
      - "3305:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=samho101
      - TZ=Asia/Seoul

  master_db1:
    platform: ubuntu:18.04
    image: mariadb:10.1
    restart: always
    container_name: master_db1
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=samho101
      - TZ=Asia/Seoul
    volumes:
      - /Users/miridih/miridih/project01/master_db1/:/etc/mysql/conf.d

  master_db2:
    platform: ubuntu:18.04
    image: mariadb:10.1
    restart: always
    container_name: master_db2
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=samho101
      - TZ=Asia/Seoul
    volumes:
      - /Users/miridih/miridih/project01/master_db2/:/etc/mysql/conf.d

  slave_db1:
    platform: ubuntu:18.04
    image: mariadb:10.1
    restart: always
    container_name: slave_db1
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=samho101
      - TZ=Asia/Seoul
    volumes:
      - /Users/miridih/miridih/project01/slave_db1/:/etc/mysql/conf.d

  slave_db2:
    platform: ubuntu:18.04
    image: mariadb:10.1
    restart: always
    container_name: slave_db2
    ports:
      - "3310:3306"
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=samho101
      - TZ=Asia/Seoul
    volumes:
      - /Users/miridih/miridih/project01/slave_db2/:/etc/mysql/conf.d