version: "3.7"
services:
  spring:
    image: openjdk:11
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "nohup java -jar build/libs/project01-0.0.1-SNAPSHOT.jar"
    restart: on-failure
    container_name: spring
    depends_on:
      - redis
      - mysql
      - flask

  flask:
    build:
      context: .
      dockerfile: ./flask/Dockerfile
    ports:
      - "6000:5000"
    container_name: flask
    volumes:
      - ./flask:/app
    working_dir: /app
    command: >
      bash -c "pip install pandas numpy flask tensorflow nltk konlpy && python server.py"
    restart: on-failure

  mysql:
    platform: linux/x86_64
    image: mysql:8
    restart: on-failure
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=project01
      - MYSQL_ROOT_PASSWORD=samho101
      - TZ=Asia/Seoul
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /home/ubuntu/project01/mysql:/var/lib/mysql

  redis:
    image: redis
    restart: on-failure
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/project01/redis:/var/lib/redis