spring:
  profiles:
    active: docker
  datasource:
    username: root
    password: samho101
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:/mapper/*.xml

youtube:
  oauth_server: https://accounts.google.com/o/oauth2
  client_id: 198658285628-fhaur6ctnljr5kf1867sf57e84c02vco.apps.googleusercontent.com
  client_pwd: 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
  redirect_url: http://localhost:8080/youtube/redirect
  api_key: AIzaSyDbfW37L3-gRuKPrvU2yZDVP_ySxr1wttU
