spring:
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  profiles:
    active: local
  datasource:
    username: root
    password: samho101
  cache:
    redis:
      time-to-live: 300000
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: create-drop
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
mybatis:
  mapper-locations: classpath:/mapper/*.xml
youtube:
  oauth_server: https://accounts.google.com/o/oauth2
  client_id: 198658285628-fhaur6ctnljr5kf1867sf57e84c02vco.apps.googleusercontent.com
  client_pwd: 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
  redirect_url: http://localhost:8080/youtube/redirect
  api_key: AIzaSyDbfW37L3-gRuKPrvU2yZDVP_ySxr1wttU