version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6000:5000"
    container_name: flask
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "pip install pandas numpy flask tensorflow nltk konlpy && python server.py"
    restart: always